### ISSUE TITLE
Coordinate class in spring_boot_datamongotest is not correct

### ISSUE THREAD

**Issue by saro199** [Farbauti89/blog_code#1]
The class name starts with public record Coordinate.

**Comment by Farbauti89** [comment]
Hi @saro199,

Thanks for addressing this issue!
Could you please elaborate on what you mean by "is not correct"?

**Comment by saro199** [comment]
I am sorry @Farbauti89 
I did not realize there is a concept of record in Java 17. My bad :) still learning.
